### ISSUE TITLE
Support 2020.2

### ISSUE THREAD

**Issue by JohannesBeranek** [tomas-milata/intelliroutes#10]
Currently doesn't work with 2020.2 - intellij reports the plugin as incompatible and won't list it for installation again after removing the current version.

**Comment by tomas-milata** [comment]
Thanks for reporting.

I've just released a [stable version](https://plugins.jetbrains.com/plugin/10053-play-routes/versions/stable/93869) that supports 2020.2 but it's still pending approval.

In the meantime, you can get this [alpha version](https://plugins.jetbrains.com/plugin/10053-play-routes/versions/alpha/93868).

**Comment by tomas-milata** [comment]
The [update](https://plugins.jetbrains.com/plugin/10053-play-routes/versions/stable) is now live.
