### ISSUE TITLE
Overrides go to support from play framework plugin

### ISSUE THREAD

**Issue by JohannesBeranek** [tomas-milata/intelliroutes#12]
When only using the play framework plugin, I can ctrl+click the controller method names in teh routes file and it will take me there ; the routes file will be without any syntax highlighting whatsoever.
When adding intelliroutes, ctrl + click won't work anymore ("Cannot find declaration to go to"), but I will get syntax highlighting.

Is there a way to preserve the linking done by the play framework plugin, or provide a working one?

Thanks a lot!

**Comment by JohannesBeranek** [comment]
Actually I see you got your own handler, but for some reason it seems it doesn't (always?) work:
RoutesGotoControllerHandler.kt
I can see the added context menu item, but when I click it, I get the same error about not being able to find the declaration to go to.

**Comment by tomas-milata** [comment]
Hi, are you referring to the Play framework support which is part of the [Scala plugin in IntelliJ Ultimate](https://plugins.jetbrains.com/plugin/1347-scala)?  My plugin is meant to be a free alternative for those who don't have the Ultimate license. I don't see a good reason to use my plugin in the Ultimate version. Or am I missing something? If people have good use case for my plugin alongside the paid one, I'd be keen to know.

**Comment by JohannesBeranek** [comment]
@tomas-milata no, I'm using Play 1 non-scala with this plugin: https://plugins.jetbrains.com/plugin/14583-play-framework/ on intellij idea ultimate. I don't think the one which comes with the scala plugin would work, as afaik that is for Play 2 or am I wrong there? Looks to me like play 1 support was dropped in intellij itself some time ago, but is still provided via their free plugin.

**Comment by JohannesBeranek** [comment]
Also: https://www.jetbrains.com/help/idea/play.html
"Support for developing Web applications based on the Play framework is not bundled with IntelliJ IDEA. You can install the Play Framework plugin from the JetBrains repository as described inManage plugins."
But I've been confused about the situation regarding Play Framework 1.x since the beginning, so I'd be very grateful if you know more.

**Comment by tomas-milata** [comment]
Oh, I see. Sorry to disappoint you, but I never intended to support Play 1. Maybe I should make it clear in the docs or on the plugin website.

I don't use Play 1 myself, so I don't even have the sufficient knowledge to have an estimate of what it would take to support it. But I'm very sceptical about it.

**Comment by tomas-milata** [comment]
I tried to summarise all I know about Play plugins and compatibility with IntelliJ editions in https://github.com/tomas-milata/intelliroutes#ide-compatibility. I hope it helps.
