### ISSUE TITLE
Plugin error when I upgrade IntelliJ 

### ISSUE THREAD

**Issue by KingHO2359** [tomas-milata/intelliroutes#14]
I have a problem with plugin when I upgrade IDE.
Please help me to fix that.
Many thanks.
![image](https://user-images.githubusercontent.com/36753313/127314160-99d8b1d4-52ea-49b8-a565-ebdd2d522374.png)

![image](https://user-images.githubusercontent.com/36753313/127314328-948b87da-2bba-44cd-a9cf-3686afbd48d9.png)

**Comment by tomas-milata** [comment]
Hi, thanks for reporting and sorry! I'm out on holiday and missed the recent IntelliJ release 😓. I'll see what I can do.

**Comment by tomas-milata** [comment]
I've released a fix. It should be available via the Jebtrain's plugin repository in a few days (once approved by the Jetbrains team). Or, in the meantime, you can install [this version](https://plugins.jetbrains.com/plugin/10053-play-2-routes/versions/stable/129914) directly (by downloading and installing from disk).

**Comment by KingHO2359** [comment]
Thanks so much for your response. I've installed your new version and it's all fixed.
Have a nice holiday.

**Comment by tomas-milata** [comment]
For reference, this is now available via the plugin repository (the standard way to install).
