### ISSUE TITLE
Plugin not compatible with IntelliJ IDEA 2022.1

### ISSUE THREAD

**Issue by PedroBatista** [tomas-milata/intelliroutes#18]
Hi,

After upgrade the IDE to version 2022.1 this plugin is no longer compatible.

Is there a "simple" way I can make it compatible by changing some compatibility string? ie. ( low hanging fruit )

If not, are you planning to review the possible compatibility problems soon? 

Thank you for you time.

**Comment by PedroBatista** [comment]
I've managed to update the plugin and make it work.

As an immediate fix until the official release is not updated you can download it here: [http://pedrobatista.eu/notes/22](http://pedrobatista.eu/notes/22)

Uninstall the current version and do "Install Plugin from Disk.."

**Comment by dpinn** [comment]
I don't feel good about using an unofficial release, but I look forward to upgrading to the official one when it is available.

**Comment by tomas-milata** [comment]
Hey all, sorry it took me a while to get to this and thanks for reporting.

There's a new release (`2022.1.0`) available in the plugin marketplace now that fixes this. Please let me know if you run into issues.

**Comment by PedroBatista** [comment]
Hi Tomas,

I've been using your new release for a few days without any issues. I think we can close this one now 🙂

Thank you for your work.
