### ISSUE TITLE
Add support of *.routes file

### ISSUE THREAD

**Issue by pharmazone** [tomas-milata/intelliroutes#3]
Plugin supports only `routes` files.

It will be great to have support all `*.routes` files

![screenshot 2017-11-29 14 35 33](https://user-images.githubusercontent.com/138582/33375484-b1c235f8-d512-11e7-8c3a-63621ae7c7a1.png)

**Comment by tomas-milata** [comment]
Good point, that's an easy fix, I'll add it.

**Comment by tomas-milata** [comment]
I've released a new version which supports also `*.routes`. The update should be available in the plugin repository in a few days, depends on how quickly Jetbrains guys review the update.

**Comment by pharmazone** [comment]
Thanks! Looking forward!

**Comment by tomas-milata** [comment]
Available now.
