### ISSUE TITLE
Support for 2019.1 release

### ISSUE THREAD

**Issue by balane** [tomas-milata/intelliroutes#6]
Please update for 2019.1 EAP

**Comment by tomas-milata** [comment]
Thanks for flagging this up and sorry for late answer. 

A version that supports 2019.1 EAP is now available in the alpha channel.

You'll have to add `https://plugins.jetbrains.com/plugins/alpha/10053` channel using Preferences > Plugins > Manage Plugin Repositories.

**Comment by balane** [comment]
I added that channel but it's failing to download the plugin with status code 400.

**Comment by tomas-milata** [comment]
Interesting, I can't reproduce on my `#IC-191.5701.16`. This works fine 
![image](https://user-images.githubusercontent.com/6483817/53121436-8b2cba00-3554-11e9-9b1c-72db8984ac11.png)

I'm not sure I can help without more details, but a 400 seems like a problem either of your current IDE version or JetBrains' plugin repo where the plugin is hosted, neither of which I'm in control of. Can you send details about your IDE version?

Alternatively, you could try downloading the plugin manually from https://plugins.jetbrains.com/plugin/download?rel=true&updateId=57665 and installing from disk.

**Comment by balane** [comment]
Sorry, just needed to restart IDEA after adding the alpha channel. Working now.
