### ISSUE TITLE
EAP not supported

### ISSUE THREAD

**Issue by balane** [tomas-milata/intelliroutes#8]
Please add support for the current EAP (2019.3)

**Comment by tomas-milata** [comment]
Hi, thanks for reporting.

For now on, there should be an alpha version supporting 2019.3 EAP available.

You can install it by adding a custom plugin repository with this URL: https://plugins.jetbrains.com/plugins/alpha/10053. Or by downloading from https://plugins.jetbrains.com/plugin/10053-play-routes/versions (click Alpha first to see alpha versions) and installing manually from disk.
