### ISSUE TITLE
"Cannot resolve" error when controller function has 2 arguments

### ISSUE THREAD

**Issue by LLCampos** [tomas-milata/intelliroutes#9]
The following method is in a controller:

```scala
  def someMethod(Argument1: Int, Argument2: Int): Action[AnyContent] = {
    ???
  }
```

But this happens:

![image](https://user-images.githubusercontent.com/12008784/74520092-cf0b9280-4f0e-11ea-891f-00aa9af441a0.png)

I wouldn't expect the `Argument2` to be red.

**Comment by tomas-milata** [comment]
Hi, thanks for reporting. I wasn't able to reproduce your example unfortunately.

Could you please try to:

- Try opening the `routes` file from this example project https://github.com/tomas-milata/intelliroutes-reproduce-issue-9.
- I you see an error on that example, could you install https://plugins.jetbrains.com/plugin/227-psiviewer, then in the `routes` file run a _PSI Dump to clipboard_ action and send the output. E.g. by right clicking in the text editor > _PSI Viewer_ > _PSI Dump to clipboard_. It should give you output similar to this:

```
Routes File(0,102)
  RoutesRouteImpl(ROUTE)(0,101)
    PsiElement(HTTP verb)('POST')(0,4)
    PsiWhiteSpace(' ')(4,5)
    RoutesPathImpl(PATH)(5,18)
      PsiElement(/)('/')(5,6)
      RoutesPathSegmentImpl(PATH_SEGMENT)(6,18)
        PsiElement(static path segment)('someEndpoint')(6,18)
    PsiWhiteSpace(' ')(18,19)
    RoutesCallImpl(CALL)(19,101)
      PsiElement(controller method)('@controllers.UserEntitlementsController.someMethod')(19,69)
      PsiElement(()('(')(69,70)
      RoutesArgumentsImpl(ARGUMENTS)(70,100)
        RoutesArgumentImpl(ARGUMENT)(70,84)
          PsiElement(argument name)('Argument1')(70,79)
          PsiElement(:)(':')(79,80)
          PsiWhiteSpace(' ')(80,81)
          PsiElement(argument type)('Int')(81,84)
        PsiElement(,)(',')(84,85)
        PsiWhiteSpace(' ')(85,86)
        RoutesArgumentImpl(ARGUMENT)(86,100)
          PsiElement(argument name)('Argument2')(86,95)
          PsiElement(:)(':')(95,96)
          PsiWhiteSpace(' ')(96,97)
          PsiElement(argument type)('Int')(97,100)
      PsiElement())(')')(100,101)
  PsiElement(new line)('\n')(101,102)
```

- If you can't reproduce the error on that example, could you please try providing a full minimal example yourself? A whole `routes` file should probably be enough.

**Comment by LLCampos** [comment]
I get errors on that example project.

![image](https://user-images.githubusercontent.com/12008784/74604026-cd2e0480-50b1-11ea-9e2e-518c02332a40.png)


The dump:

```
Play2RoutingFile(0,102)
  Play2ScalaPsiStub(ROUTING_LINE)(0,101)
    PsiElement(HTML_METHOD_NAME)('POST')(0,4)
    PsiWhiteSpace(' ')(4,5)
    Play2URIPath(ROUTING_PATH)(5,18)
      PsiElement(PATH_SLASH)('/')(5,6)
      Play2ScalaPsiNamedUrlPart(ROUTING_STATIC_REGEXP)(6,18)
        PsiElement(PATH_STATIC_IDENTIFIER)('someEndpoint')(6,18)
    PsiWhiteSpace(' ')(18,19)
    PsiElement(MANUALLY_MANAGED_AT)('@')(19,20)
    MethodCall(20,101)
      ReferenceExpression: controllers.UserEntitlementsController.someMethod(20,69)
        ReferenceExpression: controllers.UserEntitlementsController(20,58)
          ReferenceExpression: controllers(20,31)
            PsiElement(identifier)('controllers')(20,31)
          PsiElement(.)('.')(31,32)
          PsiElement(identifier)('UserEntitlementsController')(32,58)
        PsiElement(.)('.')(58,59)
        PsiElement(identifier)('someMethod')(59,69)
      ArgumentList(69,101)
        PsiElement(()('(')(69,70)
        TypedStatement(70,84)
          ReferenceExpression: Argument1(70,79)
            PsiElement(identifier)('Argument1')(70,79)
          PsiElement(:)(':')(79,80)
          PsiWhiteSpace(' ')(80,81)
          SimpleType: Int(81,84)
            CodeReferenceElement: Int(81,84)
              PsiElement(identifier)('Int')(81,84)
        PsiElement(,)(',')(84,85)
        PsiWhiteSpace(' ')(85,86)
        TypedStatement(86,100)
          ReferenceExpression: Argument2(86,95)
            PsiElement(identifier)('Argument2')(86,95)
          PsiElement(:)(':')(95,96)
          PsiWhiteSpace(' ')(96,97)
          SimpleType: Int(97,100)
            CodeReferenceElement: Int(97,100)
              PsiElement(identifier)('Int')(97,100)
        PsiElement())(')')(100,101)
  PsiWhiteSpace('\n')(101,102)
```

Some info about my IntelliJ:
```
IntelliJ IDEA 2019.3.3 (Ultimate Edition)
Build #IU-193.6494.35, built on February 11, 2020
Licensed to Luis Campos
Subscription is active until February 28, 2020
Runtime version: 11.0.5+10-b520.38 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-76-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1925M
Cores: 8
Registry: 
Non-Bundled Plugins: Karma, PsiViewer, Pythonid, org.intellij.scala, com.github.tomasmilata.intelliroutes, com.intellij.lang.puppet, de.netnexus.camelcaseplugin, mobi.hsz.idea.gitignore, org.jetbrains.plugins.hocon, org.jetbrains.plugins.ruby
```

**Comment by tomas-milata** [comment]
Thanks for providing the details.

The problem in your case is that the scala plugin in IntelliJ Ultimate has built-in support for Play (unlike the Community version) and as a result, both plugins are trying to associate their editors with `routes` files. So what you are seeing is actually a routes file editor from the Scala plugin, not this one.

I am not sure how to handle conflicting file associations on my side at the moment, so I'd recommend:

- either associating routes files to my plugin using _File_ > _Associate with File Type_ > edit the file pattern to `*.routes` (or any other pattern you'd like to associate) > select _Play Framework Routes_
<img width="568" alt="Screenshot 2020-02-16 at 13 41 10" src="https://user-images.githubusercontent.com/6483817/74604924-218db000-50c3-11ea-99e2-108f9b4896ac.png">

- or filing a bug in the Scala plugin (I believe it's https://plugins.jetbrains.com/plugin/1347-scala) and using just that plugin

**Comment by LLCampos** [comment]
Thanks! 

Here is what worked for me:

1. Go to `File -> Settings -> Editor -> File Types`
1. Search for `Html Routing Support For Play 2 Framework`
1. Remove de registered pattern from there

![image](https://user-images.githubusercontent.com/12008784/74638053-1be7a700-5163-11ea-98b6-4fee8ceaddd8.png)

1. Search for `Play Framework Routes`
1. Add `routes` to `Registered patterns`

![image](https://user-images.githubusercontent.com/12008784/74638124-3b7ecf80-5163-11ea-9c94-fbb25c6484a3.png)

**Comment by tomas-milata** [comment]
Great, thanks for sharing this!
